// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fwujbjyabjzmrfuoppmx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ3dWpianlhYmp6bXJmdW9wcG14Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NDAyOTYsImV4cCI6MjA2MTUxNjI5Nn0.OGp7sLBiE0keo09JFQJ0e0RBT2tdnBhFBpWFw2YN4wE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);